site_name: Rubika Bot Father
theme:
  name: material
  font:
    text: B Nazanin

  palette:
  - scheme: default
    primary: purple
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    primary: purple
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
#  icon:
#    repo: fontawesome/brands/github-alt
  logo: img/rubika.png
  favicon: img/rubika.png
  language: fa

nav:
- معرفی: index.md
#- معرفی: introduction.md
- متد ها: methods.md
- مدل ها: models.md

#repo_name: AliRn76/rubika-bot
#repo_url: https://github.com/AliRn76/rubika-bot

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs

#    custom_fences:
#    - direction: ltr
#    - name: mermaid
#      class: mermaid
#      format: !!python/name:pymdownx.superfences.fence_code_format {kwds: {mode: generic, tag: pre}}
- pymdownx.tabbed:
    alternate_style: true
#extra:
#  alternate:
#  - link: /en/
#    name: English
#    lang: en
#  - link: /
#    name: Persian
#    lang: fa
extra_css:
- https://fastapi.tiangolo.com/css/termynal.css
- https://fastapi.tiangolo.com/css/custom.css
extra_javascript:
- https://fastapi.tiangolo.com/js/termynal.js
- https://fastapi.tiangolo.com/js/custom.js